[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rehan Halai", email = "halairehan01@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic-settings>=2.15.0",
    "python-multipart>=0.0.32",
    "uvicorn[standard]>=0.52.4",
]

[tool.uv]
package = false
